---
name: test shell versus interpolation

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:

jobs:
  test-interp:
    strategy:
      fail-fast: false
      matrix:
        mymatrixvar:
          - hello
          - world
    runs-on: ubuntu-latest
    name: interpolation party / ${{ matrix.mymatrixvar }}
    env:
      MYVAR: "this is my variable"
    steps:
      - name: print MYVAR
        run: |
          echo "${MYVAR}"
      - name: print mymatrixvar
        run: |
          echo ${{ matrix.mymatrixvar }}
      - name: print mymatrixvar single quote
        run: |
          echo '${{ matrix.mymatrixvar }}'
      - name: print mymatrixvar double quote
        run: |
          echo "${{ matrix.mymatrixvar }}"
